public with sharing class Constants {
    public static string HTTP_STATUS_OK = 'OK';
    public static string HTTP_STATUS_UNAUTHORIZED = 'UNAUTHORIZED';
    public static Integer HTTP_STATUS_CODE_SUCCESS = 201;
    public static Integer HTTP_STATUS_CODE_FAIL = 500;
}
// key: 3MVG9Nk1FpUrSQHdU6Gik7yQ98Geup5ZtBZkj_wQd8RJRNhBP4vU1d29MG9Eu3YnY4hg8WsdorZG081eNz8Ib
// secret: 73E240484DD2C7ACA03C4A9C4F9DFB419B38A2C44F1F921DFC1230F442D87AF1
